"""Add some changes to models

Revision ID: d62000973925
Revises: 001
Create Date: 2023-07-05 01:05:57.517105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62000973925'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_title', table_name='videos')
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.create_index('ix_videos_title', 'videos', ['title'], unique=False)
    # ### end Alembic commands ###
